#!/bin/bash
current_dir="$(cd "$(dirname "$0")" && pwd)"
source "$current_dir/modules/shared"
# SETTINGS #
version=$1
container_tag="umlatt/peon.orc"
dockerfile_path="$(dirname "$current_dir")"
# EXECUTE SCRIPT #
build_container_image